apiVersion: v1
kind: Service
metadata:
  name: bookmate-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: bookmate-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP
