apiVersion: v1
kind: Secret
metadata:
  name: bookmate-secrets
  namespace: { { .Values.namespace } }
type: Opaque
stringData:
  secret-key: { { .Values.secrets.secretKey | quote } }
  database-url: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
  postgres-password: { { .Values.postgres.password | quote } }
  openai-api-key: { { .Values.secrets.openaiApiKey | quote } }
  openai-model: { { .Values.secrets.openaiModel | quote } }
