# ============================================
# Bookmate Frontend - 프로덕션 환경 오버라이드
# ============================================
# 사용법: helm install bookmate-frontend . -f values.yaml -f values-prod.yaml

namespace: bookmate-prod
frontend:
  tag: prod-b04ff5a80ea10de921c9316cc71f236770aaa936
  replicas: 2
  image: ghcr.io/jeongsoheeme/bookmate-frontend
adminFrontend:
  tag: prod-b04ff5a80ea10de921c9316cc71f236770aaa936
  replicas: 1
  image: ghcr.io/jeongsoheeme/bookmate-admin-frontend
ingress:
  enabled: true
  host: bookmate.example.com
