# ============================================
# Bookmate Frontend - 프로덕션 환경 오버라이드
# ============================================
# 사용법: helm install bookmate-frontend . -f values.yaml -f values-prod.yaml

namespace: bookmate-prod
frontend:
  tag: prod-9f38a556637800f7ef2be7a21165b667ebe6e170
  replicas: 2
  image: ghcr.io/jeongsoheeme/bookmate-frontend
adminFrontend:
  tag: prod-9f38a556637800f7ef2be7a21165b667ebe6e170
  replicas: 1
  image: ghcr.io/jeongsoheeme/bookmate-admin-frontend
ingress:
  enabled: true
  host: bookmate.example.com
