# ============================================
# Bookmate Frontend - 프로덕션 환경 오버라이드
# ============================================
# 사용법: helm install bookmate-frontend . -f values.yaml -f values-prod.yaml

namespace: bookmate-prod
frontend:
  tag: prod-588ea408e88e373cdc271fcbe47c89d9a11077c0
  replicas: 2
  image: ghcr.io/jeongsoheeme/bookmate-frontend
adminFrontend:
  tag: prod-588ea408e88e373cdc271fcbe47c89d9a11077c0
  replicas: 1
  image: ghcr.io/jeongsoheeme/bookmate-admin-frontend
ingress:
  enabled: true
  host: bookmate.example.com
