# ============================================
# Bookmate Frontend - 프로덕션 환경 오버라이드
# ============================================
# 사용법: helm install bookmate-frontend . -f values.yaml -f values-prod.yaml

namespace: bookmate-prod
frontend:
  tag: prod-20e3e725d6f25b2cd4d38a9b887146b8ef4eb999
  replicas: 2
  image: ghcr.io/jeongsoheeme/bookmate-frontend
adminFrontend:
  tag: prod-20e3e725d6f25b2cd4d38a9b887146b8ef4eb999
  replicas: 1
  image: ghcr.io/jeongsoheeme/bookmate-admin-frontend
ingress:
  enabled: true
  host: bookmate.example.com
