# ============================================
# Bookmate Frontend - 프로덕션 환경 오버라이드
# ============================================
# 사용법: helm install bookmate-frontend . -f values.yaml -f values-prod.yaml

namespace: bookmate-prod
frontend:
  tag: prod-eb88f4f34728f0f73ad09e3ee4c331a57636e8fd
  replicas: 2
  image: ghcr.io/jeongsoheeme/bookmate-frontend
adminFrontend:
  tag: prod-eb88f4f34728f0f73ad09e3ee4c331a57636e8fd
  replicas: 1
  image: ghcr.io/jeongsoheeme/bookmate-admin-frontend
ingress:
  enabled: true
  host: bookmate.example.com
