# ============================================
# Bookmate Frontend - 개발 환경 오버라이드
# ============================================
# 사용법: helm install bookmate-frontend . -f values.yaml -f values-dev.yaml

namespace: bookmate

frontend:
  image: ghcr.io/jeongsoheeme/bookmate-frontend
  tag: prod-b83136c960b6740e781ddc62dc51463e913ea13d
  replicas: 1

adminFrontend:
  image: ghcr.io/jeongsoheeme/bookmate-admin-frontend
  tag: prod-b83136c960b6740e781ddc62dc51463e913ea13d
  replicas: 1

ingress:
  enabled: false
