apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmate-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: bookmate-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: bookmate-frontend
  template:
    metadata:
      labels:
        app: bookmate-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}
