apiVersion: v1
kind: Service
metadata:
  name: bookmate-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: bookmate-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP
